---
  - name: Ensure GraalVM
    unarchive:
      src: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-linux-amd64-21.0.0.2.tar.gz
      dest: /opt/
      remote_src: yes

  - name: Ensure GraalVM configured as Java alternative
    community.general.alternatives:
      name: java
      link: /usr/bin/java
      path: /opt/graalvm-ce-java11-21.0.0.2/bin/java

  - name: Ensure GraalVM's java is selected
    community.general.alternatives:
      name: java
      path: /opt/graalvm-ce-java11-21.0.0.2/bin/java