---
  - name: Add NodeJS' APT key
    apt_key:
      id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: Add Docker's APT repository
    apt_repository:
      repo: deb https://deb.nodesource.com/node_14.x focal main
      state: present
  
  - name: Install NodeJS
    apt:
      update_cache: yes
      name:
        - nodejs
      state: latest