---
  - name: Ensure key
    apt_key:
      id: 82D96E430A1F1C0F0502747E37B90EDD4E3EFAE4
      url: https://keyserver.ubuntu.com/
      state: present

  - name: Ensure PPA
    apt_repository:
      repo: deb http://ppa.launchpad.net/lutris-team/lutris/ubuntu {{ ansible_local['ubuntu_codename']['ubuntu_codename'] }} main 
      state: present

  - name: Ensure Lutris installed
    apt:
      update_cache: yes
      name: lutris
      state: present